// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RiskUserStorage is an autogenerated mock type for the RiskUserStorage type
type RiskUserStorage struct {
	mock.Mock
}

// AddBlacklist provides a mock function with given fields: ctx, userId
func (_m *RiskUserStorage) AddBlacklist(ctx context.Context, userId int) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for AddBlacklist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWatchlist provides a mock function with given fields: ctx, userId
func (_m *RiskUserStorage) AddWatchlist(ctx context.Context, userId int) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for AddWatchlist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddWhitelist provides a mock function with given fields: ctx, userId
func (_m *RiskUserStorage) AddWhitelist(ctx context.Context, userId int) error {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for AddWhitelist")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRiskUserStorage creates a new instance of RiskUserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskUserStorage {
	mock := &RiskUserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
