definitions:
  data.AuditLog:
    properties:
      actor_id:
        description: ID of the user who performed the action
        type: integer
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      occurred_at:
        type: string
      role:
        type: string
      service:
        type: string
    type: object
  data.AuditLogVerifyResponse:
    properties:
      failed_log_id:
        type: string
      is_valid:
        type: boolean
      message:
        type: string
    type: object
  data.BaseResponse:
    properties:
      code:
        type: integer
      data: {}
      err_msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin-ms/v1/merchanat/audit-logs:
    get:
      description: Retrieve audit logs with optional filtering by user, service, and
        time range.
      parameters:
      - description: User ID
        in: query
        name: user_id
        type: string
      - description: Service name
        in: query
        name: service
        type: string
      - description: Start time
        in: query
        name: start_time
        type: string
      - description: End time
        in: query
        name: end_time
        type: string
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      - description: Limit for pagination
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/data.AuditLog'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Get Audit Logs
      tags:
      - AuditLog
  /admin-ms/v1/merchant/audit-logs/verify:
    get:
      description: Verify audit logs within a specified time range.
      parameters:
      - description: Start time
        in: query
        name: start_time
        type: string
      - description: End time
        in: query
        name: end_time
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  $ref: '#/definitions/data.AuditLogVerifyResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/data.BaseResponse'
            - properties:
                data:
                  type: string
              type: object
      summary: Verify Audit Logs
      tags:
      - AuditLog
swagger: "2.0"
