// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	dao "github.com/sw5005-sus/ceramicraft-admin-mservice/server/repository/dao"
	model "github.com/sw5005-sus/ceramicraft-admin-mservice/server/repository/model"
)

// RiskUserReviewDao is an autogenerated mock type for the RiskUserReviewDao type
type RiskUserReviewDao struct {
	mock.Mock
}

// Select provides a mock function with given fields: ctx, query
func (_m *RiskUserReviewDao) Select(ctx context.Context, query *dao.RiskUserReviewQuery) ([]*model.RiskUserReview, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Select")
	}

	var r0 []*model.RiskUserReview
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dao.RiskUserReviewQuery) ([]*model.RiskUserReview, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dao.RiskUserReviewQuery) []*model.RiskUserReview); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.RiskUserReview)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dao.RiskUserReviewQuery) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dao.RiskUserReviewQuery) error); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateDecision provides a mock function with given fields: ctx, userID, decision, decisionSource
func (_m *RiskUserReviewDao) UpdateDecision(ctx context.Context, userID int, decision int8, decisionSource string) error {
	ret := _m.Called(ctx, userID, decision, decisionSource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDecision")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int8, string) error); ok {
		r0 = rf(ctx, userID, decision, decisionSource)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRiskUserReviewDao creates a new instance of RiskUserReviewDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRiskUserReviewDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *RiskUserReviewDao {
	mock := &RiskUserReviewDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
